# Generated by Django 4.1.3 on 2022-11-04 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listing_is_active_alter_listing_creation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 7, 53, 58, 595727, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
