# Generated by Django 4.0.6 on 2022-11-08 07:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_bid_bid_alter_bid_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 7, 9, 40, 77714, tzinfo=utc)),
        ),
    ]
