# Generated by Django 4.0.6 on 2022-11-08 11:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_category_alter_listing_creation_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 8, 11, 33, 48, 579678, tzinfo=utc)),
        ),
    ]
